[project]
name = "jobsquery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "paul-dottie", email = "105995806+paul-dottie@users.noreply.github.com" }
]
requires-python = ">=3.14.7"
dependencies = [
    "extruct>=0.18.0",
    "httpx2>=2.12.0",
    "jsonschema>=4.26.0",
    "lxml>=6.1.2",
    "playwright>=1.62.0",
    "pydantic>=2.13.4",
    "pyrefly>=1.2.0",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
    "selectolax>=0.4.11",
    "tldextract>=5.3.2",
]

[project.scripts]
jobsquery = "jobsquery:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
